# Sample workflow for building and deploying an Astro site to GitHub Pages
#
# To get started with Astro see: https://docs.astro.build/en/getting-started/
#
name: Deploy Astro site to pgs.sh

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: Build
    steps:
      - uses: actions/checkout@v4

      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - uses: jdx/mise-action@v2
        with:
          experimental: true

      - uses: actions/setup-node@v5
        with:
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build with Astro
        run: pnpm run build

      - name: Upload to pgs.sh
        uses: picosh/pgs-action@v3
        with:
          user: supaspoida
          key: ${{ secrets.PRIVATE_KEY }}
          src: dist/
          project: edgecompute-dev-${{ steps.vars.outputs.sha_short }}
          promote: edgecompute-dev
          retain: edgecompute-dev-
          retain_num: 1
